/* ═══════════════════════════════════════════════════════
   lang_text.js  —  Uprint Bilingual Content
   Supports: 'en' (English) | 'bn' (Bangla)
   Usage: window.LANG['en'] / window.LANG['bn']
═══════════════════════════════════════════════════════ */

window.LANG = {

    /* ────────── ENGLISH ────────── */
    en: {
      /* NAV */
      nav_how:        'How It Works',
      nav_why:        'Why Uprint',
      nav_cases:      'Use Cases',
      nav_faq:        'FAQ',
      nav_contact:    'Contact',
      nav_start:      'Start Printing',
      nav_login:      'Log In',
  
      /* HERO */
      hero_h1_1:      'Upload online —',
      hero_h1_2:      'print from a nearby kiosk',
      hero_sub:       'Upload your file from phone or desktop, choose print settings, and collect from a nearby Uprint kiosk. No pendrive. No random shop PC.',
      hero_btn1:      'Start Printing',
      hero_btn2:      'See How It Works',
      hero_badge1:    'Secured Cloud Server',
      hero_badge2:    'Upload from Mobile',
      hero_badge3:    'No Pendrive Needed',
  
      /* HERO CARDS (UI mockup labels) */
      hc_upload_lbl:  'Upload File',
      hc_upload_done: '✓ Upload complete',
      hc_settings_lbl:'Print Settings',
      hc_pages:       'Pages',
      hc_copies:      'Copies',
      hc_color:       'Color',
      hc_size:        'Size',
      hc_cost:        'Cost',
      hc_otp_lbl:     'Your OTP',
      hc_otp_hint:    'Show at kiosk to collect your print',
      hc_ready_lbl:   'Kiosk',
      hc_ready_txt:   'Ready to collect',
      hc_ready_loc:   'Uprint Outlet · CDA Avenue',
  
      /* STATS STRIP */
      stat1_num:  'Upload from Phone or Desktop',
      stat1_lbl:  'No special app required',
      stat2_num:  'Secured Cloud Server',
      stat2_lbl:  'Your file stays private',
      stat3_num:  'Set Print Options Online',
      stat3_lbl:  'Pages, copies, color — before you go',
      stat4_num:  'OTP Kiosk Pickup',
      stat4_lbl:  'Show code, collect print',
  
      /* COMPARE */
      compare_eyebrow:   'Before vs After',
      compare_h2:        'Replace the old print-shop workflow entirely',
      compare_pain_lbl:  'The old way',
      compare_pain_h3:   'Traditional print shop',
      compare_pain_1:    'Carry a pendrive — and hope the shop reader works',
      compare_pain_2:    "Log into a random shop PC you've never touched before",
      compare_pain_3:    'Transfer files via cable or unknown WhatsApp accounts',
      compare_pain_4:    'Explain print settings every time — copies, color, pages',
      compare_pain_5:    "Wait in a crowd — no idea how long it'll take",
      compare_pain_6:    'Price is a surprise — you only find out at the counter',
      compare_gain_lbl:  'With Uprint',
      compare_gain_h3:   'Cloud printing done right',
      compare_gain_1:    'Upload from your own phone or desktop — no pendrive at all',
      compare_gain_2:    'No shop PC login — your file never leaves your device',
      compare_gain_3:    "Secure digital upload to Uprint's own cloud server",
      compare_gain_4:    'Choose copies, color, pages, and size online — before you go',
      compare_gain_5:    'Walk in, enter OTP at kiosk, collect — self-service pickup',
      compare_gain_6:    'See the exact cost before you confirm the print job',
  
      /* HOW IT WORKS */
      hiw_eyebrow:  'How It Works',
      hiw_h2:       "Four steps. That's it.",
      hiw_1_title:  'Upload your file',
      hiw_1_text:   'Select a PDF, Word doc, or image from your phone or desktop and upload it to Uprint.',
      hiw_2_title:  'Choose print settings',
      hiw_2_text:   'Pick page range, copies, color or B&W, and paper size — all online, before you arrive.',
      hiw_3_title:  'Confirm & get OTP',
      hiw_3_text:   'Review the cost, confirm your job, and receive a unique OTP for kiosk pickup.',
      hiw_4_title:  'Collect from kiosk',
      hiw_4_text:   'Visit any nearby Uprint outlet, press your OTP at the kiosk, and collect your printout.',
  
      /* USE CASES */
      uc_eyebrow: 'Use Cases',
      uc_h2_1:    'What people print',
      uc_h2_2:    'with Uprint',
      uc_1_h3:    'Class Notes & Assignments',
      uc_1_p:     'Students upload lecture notes, slides, or assignment sheets and collect printed copies from the nearest Uprint point.',
      uc_2_h3:    'CVs & Job Applications',
      uc_2_p:     'Print your resume exactly the way you formatted it — no reformatting on a random shop PC before your interview.',
      uc_3_h3:    'Admit Cards & Exam Forms',
      uc_3_p:     'Upload your admit card PDF from your phone the morning of the exam and pick up a clean print at the kiosk.',
      uc_4_h3:    'Office Documents',
      uc_4_p:     'Reports, invoices, memos — upload from your work laptop and collect on the way to a meeting.',
      uc_5_h3:    'Project Reports',
      uc_5_p:     'Final-year projects, research papers, presentations — print multi-page documents with the right settings every time.',
      uc_6_h3:    'Forms & Applications',
      uc_6_p:     'Bank forms, government applications, visa documents — print clearly without any compromise in formatting.',
  
      /* PHONE FEATURE */
      phone_eyebrow: 'Self-Service Kiosk',
      phone_h2:      'Your phone is all you need',
      phone_body:    'No pendrive. No shop PC. No explaining settings at the counter. Just upload, confirm, and collect.',
      phone_s1:      'Open Uprint → <strong>upload your file</strong>',
      phone_s2:      '<strong>Choose settings</strong> — copies, color, page range',
      phone_s3:      'Get your <strong>OTP code</strong> after confirming the job',
      phone_s4:      'Visit the kiosk → <strong>enter OTP → collect print</strong>',
      phone_btn1:    'Start Printing',
      phone_btn2:    'User Manual',
      /* phone UI labels */
      phone_app_title: 'Uprint',
      phone_app_sub:   'New Print Job',
      phone_take:      'Take a Photo',
      phone_browse:    'Browse File',
      phone_confirm:   '🔐 Confirm & Get OTP',
      phone_otp_sub:   'Your OTP code',
      phone_confirmed: '✓ Confirmed',
  
      /* BENEFITS */
      ben_eyebrow: 'Why Uprint',
      ben_h2_1:    'Built for how people',
      ben_h2_2:    'actually print',
      ben_1_h3:    'No pendrive, ever',
      ben_1_p:     'Upload directly from your own device. No physical storage, no USB readers, no pendrive viruses.',
      ben_2_h3:    'Mobile-friendly upload',
      ben_2_p:     'Works in your phone browser — no app install needed to start or manage a print job.',
      ben_3_h3:    'Secured file system',
      ben_3_p:     "Your documents go to Uprint's secured cloud — never through an unknown device or shared PC.",
      ben_4_h3:    'Self-service kiosk pickup',
      ben_4_p:     'Walk in, press OTP, collect print. No waiting at the counter, no explaining anything to staff.',
      ben_5_h3:    'Cost upfront, no surprises',
      ben_5_p:     'See the exact print cost before you confirm. No price shock when you reach the outlet.',
      ben_6_h3:    'Can connect with any printer',
      ben_6_p:     'Uprint kiosks can pair with any compatible printer — flexible setup for outlets across Bangladesh.',
  
      /* FAQ */
      faq_eyebrow: 'FAQ',
      faq_h2:      'Frequently Asked Questions',
      faq_1_q:     'What is Uprint?',
      faq_1_a:     'Uprint is a cloud-based printing solution in Bangladesh. You upload your document from your phone or computer, choose print settings, get an OTP, and collect the printout from a nearby Uprint kiosk — without needing a pendrive or touching a shop PC.',
      faq_2_q:     'Can I upload from my phone?',
      faq_2_a:     "Yes. Uprint is designed to work from your phone browser. Upload files from your gallery, files app, or cloud storage. There's also a dedicated mobile app on the Google Play Store if you prefer.",
      faq_3_q:     'Do I need to visit the kiosk first?',
      faq_3_a:     'No. The upload, settings, and confirmation all happen online from your own device first. You only visit the kiosk at the end — to press your OTP and collect the printout.',
      faq_4_q:     'What file types can I print?',
      faq_4_a:     'Uprint supports common document formats including PDF, Word (.docx), and image files (JPG, PNG). PDF is recommended for the most accurate output — especially for admit cards, forms, and formatted documents.',
      faq_5_q:     'How does the OTP pickup work?',
      faq_5_a:     'After confirming your print job, Uprint gives you a unique OTP code. Visit any Uprint kiosk, press your OTP on the kiosk screen, and it releases your printout. No need to speak to anyone or explain your job.',
      faq_6_q:     'Do I need a pendrive?',
      faq_6_a:     "No — that's the whole point of Uprint. You upload from your own device directly. No physical storage is required at any step of the process.",
      faq_7_q:     'How much does printing cost?',
      faq_7_a:     'Uprint shows you the exact cost estimate before you confirm any print job — based on your chosen settings (pages, copies, color/B&W). Online payment is also supported so you can pay before reaching the kiosk.',
  
      /* FINAL CTA */
      fcta_eyebrow: 'Get Started',
      fcta_h2_1:    'Ready to print without',
      fcta_h2_2:    'the usual hassle?',
      fcta_p:       'Upload your file. Choose your settings. Get an OTP. Collect at the kiosk. Simple as that.',
      fcta_btn1:    'Start Printing',
      fcta_btn2:    'See How It Works',
  
      /* FOOTER */
      footer_tagline:  'Cloud printing for Bangladesh. Upload from your device and collect from a nearby Uprint kiosk — no pendrive, no shop PC hassle.',
      footer_col1:     'Product',
      footer_col2:     'Account',
      footer_col3:     'Get in Touch',
      footer_f1_1:     'How It Works',
      footer_f1_2:     'Why Uprint',
      footer_f1_3:     'Use Cases',
      footer_f1_4:     'FAQ',
      footer_f1_5:     'User Manual',
      footer_f2_1:     'Sign Up',
      footer_f2_2:     'Log In',
      footer_f2_3:     'Android App',
      footer_copy:     '© 2025 Uprint · All rights reserved.',
      footer_link1:    'Privacy Policy',
      footer_link2:    'Terms of Service',
      footer_link3:    'User Manual',
      footer_addr:     '1005/2/1872 CDA Avenue, Nasirabad, Chittagong',
    },
  
    /* ────────── BANGLA ────────── */
    bn: {
      /* NAV */
      nav_how:        'কীভাবে কাজ করে',
      nav_why:        'কেন ইউপ্রিন্ট',
      nav_cases:      'ব্যবহারের ক্ষেত্র',
      nav_faq:        'প্রশ্নোত্তর',
      nav_contact:    'যোগাযোগ',
      nav_start:      'প্রিন্ট শুরু করুন',
      nav_login:      'লগ ইন',
  
      /* HERO */
      hero_h1_1:      'অনলাইনে আপলোড করুন —',
      hero_h1_2:      'কাছের কিওস্ক থেকে প্রিন্ট নিন',
      hero_sub:       'ফোন বা ডেস্কটপ থেকে ফাইল আপলোড করুন, প্রিন্ট সেটিং বেছে নিন, এবং কাছের ইউপ্রিন্ট কিওস্ক থেকে প্রিন্ট সংগ্রহ করুন। কোনো পেনড্রাইভ নেই। কোনো অচেনা দোকানের পিসি নেই।',
      hero_btn1:      'প্রিন্ট শুরু করুন',
      hero_btn2:      'কীভাবে কাজ করে দেখুন',
      hero_badge1:    'সুরক্ষিত ক্লাউড সার্ভার',
      hero_badge2:    'মোবাইল থেকে আপলোড',
      hero_badge3:    'পেনড্রাইভের প্রয়োজন নেই',
  
      /* HERO CARDS */
      hc_upload_lbl:  'ফাইল আপলোড',
      hc_upload_done: '✓ আপলোড সম্পন্ন',
      hc_settings_lbl:'প্রিন্ট সেটিং',
      hc_pages:       'পৃষ্ঠা',
      hc_copies:      'কপি',
      hc_color:       'রঙ',
      hc_size:        'সাইজ',
      hc_cost:        'খরচ',
      hc_otp_lbl:     'আপনার OTP',
      hc_otp_hint:    'প্রিন্ট নিতে কিওস্কে দেখান',
      hc_ready_lbl:   'কিওস্ক',
      hc_ready_txt:   'সংগ্রহের জন্য প্রস্তুত',
      hc_ready_loc:   'ইউপ্রিন্ট আউটলেট · সিডিএ এভিনিউ',
  
      /* STATS STRIP */
      stat1_num:  'ফোন বা ডেস্কটপ থেকে আপলোড',
      stat1_lbl:  'কোনো বিশেষ অ্যাপ লাগবে না',
      stat2_num:  'সুরক্ষিত ক্লাউড সার্ভার',
      stat2_lbl:  'আপনার ফাইল সুরক্ষিত থাকে',
      stat3_num:  'অনলাইনে প্রিন্ট অপশন সেট করুন',
      stat3_lbl:  'পৃষ্ঠা, কপি, রঙ — যাওয়ার আগেই',
      stat4_num:  'OTP দিয়ে কিওস্ক থেকে সংগ্রহ',
      stat4_lbl:  'কোড দেখান, প্রিন্ট নিন',
  
      /* COMPARE */
      compare_eyebrow:   'আগে বনাম পরে',
      compare_h2:        'পুরনো প্রিন্ট শপের ঝামেলা পুরোপুরি শেষ করুন',
      compare_pain_lbl:  'পুরনো পদ্ধতি',
      compare_pain_h3:   'সাধারণ প্রিন্ট শপ',
      compare_pain_1:    'পেনড্রাইভ নিয়ে যান — এবং আশা করুন দোকানের রিডার কাজ করবে',
      compare_pain_2:    'অপরিচিত দোকানের পিসিতে লগ ইন করুন',
      compare_pain_3:    'ক্যাবল বা অজানা WhatsApp একাউন্টে ফাইল পাঠান',
      compare_pain_4:    'প্রতিবার প্রিন্ট সেটিং বোঝান — কপি, রঙ, পৃষ্ঠা',
      compare_pain_5:    'ভিড়ে অপেক্ষা করুন — কতক্ষণ লাগবে জানেন না',
      compare_pain_6:    'কাউন্টারে গিয়ে জানতে পারেন দাম কত',
      compare_gain_lbl:  'ইউপ্রিন্টের সাথে',
      compare_gain_h3:   'ক্লাউড প্রিন্টিং সঠিকভাবে',
      compare_gain_1:    'নিজের ফোন বা ডেস্কটপ থেকে আপলোড — পেনড্রাইভ নেই',
      compare_gain_2:    'দোকানের পিসিতে লগ ইন নেই — ফাইল আপনার কাছেই থাকে',
      compare_gain_3:    'ইউপ্রিন্টের নিজস্ব ক্লাউড সার্ভারে সুরক্ষিত আপলোড',
      compare_gain_4:    'কপি, রঙ, পৃষ্ঠা, সাইজ অনলাইনে বেছে নিন — আসার আগেই',
      compare_gain_5:    'ঢুকুন, OTP দিন, প্রিন্ট নিন — সেলফ-সার্ভিস পিকআপ',
      compare_gain_6:    'প্রিন্ট নিশ্চিত করার আগেই সঠিক খরচ দেখুন',
  
      /* HOW IT WORKS */
      hiw_eyebrow:  'কীভাবে কাজ করে',
      hiw_h2:       'মাত্র চারটি ধাপ।',
      hiw_1_title:  'ফাইল আপলোড করুন',
      hiw_1_text:   'ফোন বা ডেস্কটপ থেকে PDF, Word বা ছবি বেছে ইউপ্রিন্টে আপলোড করুন।',
      hiw_2_title:  'প্রিন্ট সেটিং বেছে নিন',
      hiw_2_text:   'পৃষ্ঠা পরিসর, কপি, রঙ বা সাদা-কালো, এবং কাগজের সাইজ — সব অনলাইনে, আসার আগেই।',
      hiw_3_title:  'নিশ্চিত করুন ও OTP নিন',
      hiw_3_text:   'খরচ দেখুন, জব নিশ্চিত করুন এবং কিওস্ক পিকআপের জন্য OTP পান।',
      hiw_4_title:  'কিওস্ক থেকে সংগ্রহ করুন',
      hiw_4_text:   'কাছের যেকোনো ইউপ্রিন্ট আউটলেটে যান, কিওস্কে OTP দিন এবং প্রিন্ট নিন।',
  
      /* USE CASES */
      uc_eyebrow: 'ব্যবহারের ক্ষেত্র',
      uc_h2_1:    'ইউপ্রিন্টে মানুষ',
      uc_h2_2:    'যা প্রিন্ট করেন',
      uc_1_h3:    'ক্লাস নোট ও অ্যাসাইনমেন্ট',
      uc_1_p:     'শিক্ষার্থীরা লেকচার নোট, স্লাইড বা অ্যাসাইনমেন্ট শিট আপলোড করে কাছের ইউপ্রিন্ট পয়েন্ট থেকে প্রিন্ট সংগ্রহ করেন।',
      uc_2_h3:    'সিভি ও চাকরির আবেদন',
      uc_2_p:     'আপনার তৈরি ফরম্যাটেই সিভি প্রিন্ট করুন — ইন্টারভিউর আগে অচেনা পিসিতে রিফরম্যাটিং নেই।',
      uc_3_h3:    'প্রবেশপত্র ও পরীক্ষার ফর্ম',
      uc_3_p:     'পরীক্ষার সকালে ফোন থেকে প্রবেশপত্রের PDF আপলোড করে কিওস্ক থেকে পরিষ্কার প্রিন্ট নিন।',
      uc_4_h3:    'অফিসের কাগজপত্র',
      uc_4_p:     'রিপোর্ট, ইনভয়েস, মেমো — ল্যাপটপ থেকে আপলোড করুন, মিটিংয়ের পথে সংগ্রহ করুন।',
      uc_5_h3:    'প্রজেক্ট রিপোর্ট',
      uc_5_p:     'ফাইনাল ইয়ার প্রজেক্ট, গবেষণাপত্র, উপস্থাপনা — সব সময় সঠিক সেটিংয়ে মাল্টি-পেজ নথি প্রিন্ট করুন।',
      uc_6_h3:    'ফর্ম ও আবেদনপত্র',
      uc_6_p:     'ব্যাংক ফর্ম, সরকারি আবেদন, ভিসার কাগজ — ফরম্যাটিংয়ে কোনো আপস ছাড়াই পরিষ্কার প্রিন্ট।',
  
      /* PHONE FEATURE */
      phone_eyebrow: 'সেলফ-সার্ভিস কিওস্ক',
      phone_h2:      'আপনার ফোনই যথেষ্ট',
      phone_body:    'পেনড্রাইভ নেই। দোকানের পিসি নেই। কাউন্টারে সেটিং বোঝানো নেই। শুধু আপলোড, নিশ্চিত, এবং সংগ্রহ।',
      phone_s1:      'ইউপ্রিন্ট খুলুন → <strong>ফাইল আপলোড করুন</strong>',
      phone_s2:      '<strong>সেটিং বেছে নিন</strong> — কপি, রঙ, পৃষ্ঠা পরিসর',
      phone_s3:      'জব নিশ্চিতের পর আপনার <strong>OTP কোড</strong> পান',
      phone_s4:      'কিওস্কে যান → <strong>OTP দিন → প্রিন্ট নিন</strong>',
      phone_btn1:    'প্রিন্ট শুরু করুন',
      phone_btn2:    'ব্যবহারকারী ম্যানুয়াল',
      /* phone UI labels */
      phone_app_title: 'ইউপ্রিন্ট',
      phone_app_sub:   'নতুন প্রিন্ট জব',
      phone_take:      'ছবি তুলুন',
      phone_browse:    'ফাইল বাছুন',
      phone_confirm:   '🔐 নিশ্চিত করুন ও OTP নিন',
      phone_otp_sub:   'আপনার OTP কোড',
      phone_confirmed: '✓ নিশ্চিত হয়েছে',
  
      /* BENEFITS */
      ben_eyebrow: 'কেন ইউপ্রিন্ট',
      ben_h2_1:    'মানুষ যেভাবে সত্যিকার অর্থে',
      ben_h2_2:    'প্রিন্ট করেন সেভাবেই তৈরি',
      ben_1_h3:    'পেনড্রাইভ কখনোই নয়',
      ben_1_p:     'নিজের ডিভাইস থেকে সরাসরি আপলোড করুন। কোনো ফিজিক্যাল স্টোরেজ, USB রিডার বা পেনড্রাইভ ভাইরাস নেই।',
      ben_2_h3:    'মোবাইল-বান্ধব আপলোড',
      ben_2_p:     'ফোনের ব্রাউজারেই কাজ করে — প্রিন্ট জব শুরু বা পরিচালনার জন্য অ্যাপ ইনস্টল করতে হয় না।',
      ben_3_h3:    'সুরক্ষিত ফাইল সিস্টেম',
      ben_3_p:     'আপনার ডকুমেন্ট ইউপ্রিন্টের সুরক্ষিত ক্লাউডে যায় — কোনো অজানা ডিভাইস বা শেয়ার্ড পিসির মধ্য দিয়ে নয়।',
      ben_4_h3:    'সেলফ-সার্ভিস কিওস্ক পিকআপ',
      ben_4_p:     'ঢুকুন, OTP দিন, প্রিন্ট নিন। কাউন্টারে অপেক্ষা নেই, কাউকে কিছু বোঝাতে হয় না।',
      ben_5_h3:    'আগেই খরচ জানুন, চমক নেই',
      ben_5_p:     'নিশ্চিত করার আগেই সঠিক প্রিন্ট খরচ দেখুন। আউটলেটে পৌঁছে দামে অবাক হওয়ার ভয় নেই।',
      ben_6_h3:    'যেকোনো প্রিন্টারের সাথে সংযোগ',
      ben_6_p:     'ইউপ্রিন্ট কিওস্ক যেকোনো সামঞ্জস্যপূর্ণ প্রিন্টারের সাথে যুক্ত হতে পারে — বাংলাদেশজুড়ে আউটলেটের জন্য নমনীয় সেটআপ।',
  
      /* FAQ */
      faq_eyebrow: 'প্রশ্নোত্তর',
      faq_h2:      'সচরাচর জিজ্ঞাসা',
      faq_1_q:     'ইউপ্রিন্ট কী?',
      faq_1_a:     'ইউপ্রিন্ট বাংলাদেশের একটি ক্লাউড-ভিত্তিক প্রিন্টিং সমাধান। আপনি ফোন বা কম্পিউটার থেকে ডকুমেন্ট আপলোড করুন, প্রিন্ট সেটিং বেছে নিন, OTP পান, এবং কাছের ইউপ্রিন্ট কিওস্ক থেকে প্রিন্ট সংগ্রহ করুন — পেনড্রাইভ বা দোকানের পিসি ছাড়াই।',
      faq_2_q:     'ফোন থেকে আপলোড করা যাবে?',
      faq_2_a:     'হ্যাঁ। ইউপ্রিন্ট ফোনের ব্রাউজার থেকেই ব্যবহারের উপযোগী। গ্যালারি, ফাইল অ্যাপ বা ক্লাউড স্টোরেজ থেকে ফাইল আপলোড করুন। Google Play Store-এ একটি ডেডিকেটেড মোবাইল অ্যাপও পাওয়া যায়।',
      faq_3_q:     'আগে কি কিওস্কে যেতে হবে?',
      faq_3_a:     'না। আপলোড, সেটিং এবং নিশ্চিতকরণ সব আপনার নিজের ডিভাইস থেকে অনলাইনে হয়। শুধু শেষে কিওস্কে যান — OTP দিতে এবং প্রিন্ট সংগ্রহ করতে।',
      faq_4_q:     'কোন ধরনের ফাইল প্রিন্ট করা যায়?',
      faq_4_a:     'ইউপ্রিন্ট সাধারণ ডকুমেন্ট ফরম্যাট সাপোর্ট করে — PDF, Word (.docx) এবং ছবি (JPG, PNG)। প্রবেশপত্র, ফর্ম ও ফরম্যাট করা ডকুমেন্টের জন্য PDF সবচেয়ে নির্ভরযোগ্য।',
      faq_5_q:     'OTP দিয়ে পিকআপ কীভাবে কাজ করে?',
      faq_5_a:     'প্রিন্ট জব নিশ্চিত করার পর ইউপ্রিন্ট একটি অনন্য OTP কোড দেয়। যেকোনো ইউপ্রিন্ট কিওস্কে গিয়ে কিওস্কের স্ক্রিনে OTP দিন — প্রিন্ট বেরিয়ে আসবে। কাউকে কিছু বলতে বা বোঝাতে হবে না।',
      faq_6_q:     'পেনড্রাইভ কি লাগবে?',
      faq_6_a:     'না — এটাই ইউপ্রিন্টের মূল উদ্দেশ্য। আপনি সরাসরি নিজের ডিভাইস থেকে আপলোড করেন। প্রক্রিয়ার কোনো ধাপেই ফিজিক্যাল স্টোরেজ প্রয়োজন নেই।',
      faq_7_q:     'প্রিন্টের খরচ কত?',
      faq_7_a:     'যেকোনো প্রিন্ট জব নিশ্চিত করার আগেই ইউপ্রিন্ট সঠিক খরচ দেখায় — আপনার বেছে নেওয়া সেটিং (পৃষ্ঠা, কপি, রঙ/সাদা-কালো) অনুযায়ী। অনলাইন পেমেন্টও সাপোর্টেড, কিওস্কে পৌঁছানোর আগেই পেমেন্ট করা যায়।',
  
      /* FINAL CTA */
      fcta_eyebrow: 'শুরু করুন',
      fcta_h2_1:    'সাধারণ ঝামেলা ছাড়াই',
      fcta_h2_2:    'প্রিন্ট করতে প্রস্তুত?',
      fcta_p:       'ফাইল আপলোড করুন। সেটিং বেছে নিন। OTP পান। কিওস্ক থেকে সংগ্রহ করুন। এটুকুই।',
      fcta_btn1:    'প্রিন্ট শুরু করুন',
      fcta_btn2:    'কীভাবে কাজ করে দেখুন',
  
      /* FOOTER */
      footer_tagline:  'বাংলাদেশের জন্য ক্লাউড প্রিন্টিং। আপনার ডিভাইস থেকে আপলোড করুন এবং কাছের ইউপ্রিন্ট কিওস্ক থেকে সংগ্রহ করুন — পেনড্রাইভ নেই, দোকানের পিসির ঝামেলা নেই।',
      footer_col1:     'পণ্য',
      footer_col2:     'একাউন্ট',
      footer_col3:     'যোগাযোগ করুন',
      footer_f1_1:     'কীভাবে কাজ করে',
      footer_f1_2:     'কেন ইউপ্রিন্ট',
      footer_f1_3:     'ব্যবহারের ক্ষেত্র',
      footer_f1_4:     'প্রশ্নোত্তর',
      footer_f1_5:     'ব্যবহারকারী ম্যানুয়াল',
      footer_f2_1:     'নিবন্ধন করুন',
      footer_f2_2:     'লগ ইন',
      footer_f2_3:     'Android অ্যাপ',
      footer_copy:     '© ২০২৫ ইউপ্রিন্ট · সর্বস্বত্ব সংরক্ষিত।',
      footer_link1:    'গোপনীয়তা নীতি',
      footer_link2:    'ব্যবহারের শর্তাবলী',
      footer_link3:    'ব্যবহারকারী ম্যানুয়াল',
      footer_addr:     '১০০৫/২/১৮৭২ সিডিএ এভিনিউ, নাসিরাবাদ, চট্টগ্রাম',
    }
  };